default:
  module: "src.language_models.instance.openai_language_model.OpenaiLanguageModel"
  parameters:
    role_dict:
      # https://platform.openai.com/docs/guides/text-generation#messages-and-roles
      user: "user"
      agent: "assistant"
    # api_key: ~  # Enter your API key here or set in as an environment variable (OPENAI_API_KEY). Do not commit your API key!!!
    base_url: https://api.openai.com/v1#
    # base_url: ~
    disable_api_tools: true  # Always disable API tool calling

gpt-oss:20b-64k:
  parameters:
    model_name: "gpt-oss:20b-64k"
    maximum_prompt_token_count: 64000   # override per model if needed


gpt-oss:20b-120k:
  parameters:
    model_name: "gpt-oss:20b-120k"
    maximum_prompt_token_count: 120000   # override per model if needed


gpt-5-mini:
  parameters:
    model_name: "gpt-5-mini"

gpt-5.2:
  parameters:
    model_name: "gpt-5.2"

#completion_config_dict:
#  max_completion_tokens: 512
